@startuml
!include <C4/C4_Context>

LAYOUT_WITH_LEGEND()

Person(praesident, "Präsident", "Plant Saison und Wettkämpfe")
Person(verein, "Verein", "Meldet Kinder an")
Person(punktrichter, "Punktrichter", "Verwaltet Wettkampf vor Ort")
Person(kampfrichter, "Kampfrichter", "Bewertet Starts")
Person(kind, "Kind", "Nimmt am Wettkampf teil")
Person(kind, "Kind", "meldet sich an")

System(aquarius, "Aquarius", "Bewertungssystem für Kunds- und Figurenschwimmen")

System_Ext(schwimmverband, "Schwimmverband", "Figuren und Regeln")

Rel(praesident, aquarius, "Plant Saison, verwaltet Stammdaten")
Rel_U(verein, aquarius, "organisiert Teams" )
Rel_U(Eltern, aquarius, "Melden Kinder an")
Rel(punktrichter, aquarius, "Führt Wettkampf durch", "offline")
Rel(kampfrichter, aquarius, "Erfasst Punkte", "offline")
Rel_R(kind, aquarius, "Sieht Ergebnisse")

Rel_L(schwimmverband, aquarius, "Figurenkatalog, Regeln", "Manuell")

@enduml
