@startuml
!define ENTITY class
!define PK <u>
!define FK

' Stammdaten
ENTITY Club {
  PK id
  name
}

ENTITY Team {
  PK id
  name
  FK club_id
}

ENTITY Child {
  PK id
  name
  first_name
  birth_date
  address
  FK team_id
}

ENTITY Official {
  PK id
  name
  phone
}

' Saisonplanung
ENTITY Season {
  PK id
  name
  from_date
  to_date
}

ENTITY Pool {
  PK id
  phone_no
  manager
}

ENTITY Competition {
  PK id
  date
  location
  max_participants
  FK season_id
  FK pool_id
}

ENTITY Figure {
  PK id
  difficulty
}

' Anmeldung
ENTITY Enrollment {
  PK id
  starting_no
  preliminary
  enrol_time
  FK child_id
  FK competition_id
}

' Wettkampf (Competition Organization)
ENTITY Station {
  PK id
  name
  location
}

ENTITY StationChief {
  PK id
  FK official_id
  FK station_id
}

ENTITY Round {
  PK id
  starttime
  FK station_id
  FK group_id
}

ENTITY Group {
  PK id
}

' Bewertung
ENTITY ScoringJudge {
  PK id
  FK official_id
}

ENTITY Performance {
  PK id
  score
  prelim_score
  FK round_id
  FK enrollment_id
}

' Relationships
Club "1" -- "*" Team : contains
Team "1" -- "*" Child : has
Child "*" -- "*" Enrollment : registers

Season "1" -- "*" Competition : has
Pool "1" -- "*" Competition : hosts
Competition "*" -- "*" Figure : planned_figure

Competition "1" -- "*" Enrollment : enrollment

Competition "1/*" -- "*" Round : organization
Station "1" -- "*" Round : hosts
Station "1" -- "1" StationChief : station_responsibility
Group "1" -- "*" Round : presentation

Round "*" -- "3..*" ScoringJudge : scoring_judge_assignment
Round "1" -- "*" Performance : judging

Enrollment "*" -- "*" Figure : wanted_figure
Enrollment "1" -- "*" Performance : performs

Official "1" -- "*" StationChief : is_a
Official "1" -- "*" ScoringJudge : is_a

@enduml
